@PORT = 3000

### User teljesítményeinek statisztikája
GET http://localhost:{{PORT}}/user_statistics/statistics/0065ff09-5188-4591-b5de-1dc37c746658
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwNjVmZjA5LTUxODgtNDU5MS1iNWRlLTFkYzM3Yzc0NjY1OCIsImVtYWlsIjoiZHVkYXNsZXZlbnRlQHR1cnIuaHUiLCJyb2xlIjoidXNlciIsIm5hbWUiOiJEdWTDoXMgTGV2ZW50ZSIsImlhdCI6MTc0NzIxMDM0NiwiZXhwIjoxNzQ3Mjk2NzQ2fQ.Z0d48rwtxJa_0hbXp2vh1HS9oDboEuONtbrSP3TmW7g

### User szokás statisztikája
GET http://localhost:{{PORT}}/user_statistics/habit/0065ff09-5188-4591-b5de-1dc37c746658
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwNjVmZjA5LTUxODgtNDU5MS1iNWRlLTFkYzM3Yzc0NjY1OCIsImVtYWlsIjoiZHVkYXNsZXZlbnRlQHR1cnIuaHUiLCJyb2xlIjoidXNlciIsIm5hbWUiOiJEdWTDoXMgTGV2ZW50ZSIsImlhdCI6MTc0NzIxMDM0NiwiZXhwIjoxNzQ3Mjk2NzQ2fQ.Z0d48rwtxJa_0hbXp2vh1HS9oDboEuONtbrSP3TmW7g

### User kihívás statisztikája
GET http://localhost:{{PORT}}/user_statistics/challenges/0065ff09-5188-4591-b5de-1dc37c746658
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwNjVmZjA5LTUxODgtNDU5MS1iNWRlLTFkYzM3Yzc0NjY1OCIsImVtYWlsIjoiZHVkYXNsZXZlbnRlQHR1cnIuaHUiLCJyb2xlIjoidXNlciIsIm5hbWUiOiJEdWTDoXMgTGV2ZW50ZSIsImlhdCI6MTc0NzIxMDM0NiwiZXhwIjoxNzQ3Mjk2NzQ2fQ.Z0d48rwtxJa_0hbXp2vh1HS9oDboEuONtbrSP3TmW7g

### Felhasználó statisztikájának frissítése befejezett feladattal
POST http://localhost:{{PORT}}/user_statistics/completedTask
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwNjVmZjA5LTUxODgtNDU5MS1iNWRlLTFkYzM3Yzc0NjY1OCIsImVtYWlsIjoiZHVkYXNsZXZlbnRlQHR1cnIuaHUiLCJyb2xlIjoidXNlciIsIm5hbWUiOiJEdWTDoXMgTGV2ZW50ZSIsImlhdCI6MTc0NzIxMDM0NiwiZXhwIjoxNzQ3Mjk2NzQ2fQ.Z0d48rwtxJa_0hbXp2vh1HS9oDboEuONtbrSP3TmW7g

### Felhasználó statisztikájának frissítése befejezetlen feladattal
POST http://localhost:{{PORT}}/user_statistics/missedTask
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwNjVmZjA5LTUxODgtNDU5MS1iNWRlLTFkYzM3Yzc0NjY1OCIsImVtYWlsIjoiZHVkYXNsZXZlbnRlQHR1cnIuaHUiLCJyb2xlIjoidXNlciIsIm5hbWUiOiJEdWTDoXMgTGV2ZW50ZSIsImlhdCI6MTc0NzIxMDM0NiwiZXhwIjoxNzQ3Mjk2NzQ2fQ.Z0d48rwtxJa_0hbXp2vh1HS9oDboEuONtbrSP3TmW7g